#143 track health on dogu cr
cloudogu/k8s-dogu-operator pull request #144
Opened 2023-12-18 15:28 UTC by jelemux

Resolves #143

2023-12-20 11:04 UTC, alexander-dammeier requested changes
Please check the kubebuilder version.

The rest looks good :)

2024-01-03 10:44 UTC, jelemux commented on api/v1/k8s.cloudogu.com_dogus.yaml
> +    controller-gen.kubebuilder.io/version: v0.11.3
I had an older controller-gen installed locally. Upgraded and regenerated now.

2024-01-03 10:50 UTC, jelemux commented on controllers/health/availability.go
> +type AvailabilityChecker struct{}
I use it so I can encapsulate this complexity more easily and mock its behaviour. But maybe, mocking it is more trouble than simply using it directly as a function. Should I change this?

2024-01-03 14:09 UTC, alexander-dammeier commented
the availability checker can stay this way. We can further refactor this in the future if it is too much abstraction.
The rest looks good to me.

2024-01-03 14:09 UTC, merged