Add startup and liveness probes based on dogu.json "Healthchecks" entries
cloudogu/k8s-dogu-operator pull request #16
Opened 2022-05-11 08:36 UTC by robertauer

### Added
- Add startup probe based on state at dogu deployment generation; #15
- Add liveness probe based on tcp port at dogu deployment generation; #15

Resolves #15

2022-05-11 13:04 UTC, ppxl requested changes
This looks like a nice and lean solution! Maybe we should look into visibility of structs and methods, though.

2022-05-11 13:04 UTC, ppxl commented on controllers/resource/resource_generator_test.go
> +	_ "embed"
:+1:

2022-05-11 13:11 UTC, robertauer commented on controllers/dependency/dogu_dependency_validator.go
> +type DoguDependencyChecker interface {
@nhinze23

2022-05-11 13:11 UTC, robertauer commented on controllers/dependency/dogu_dependency_validator.go
>  }
@nhinze23

2022-05-11 13:12 UTC, robertauer commented on controllers/resource/resource_generator_test.go
> +	_ "embed"
All credits go to my IDE :D

2022-05-12 06:45 UTC, ppxl commented
LGTM

2022-05-12 06:45 UTC, merged