Use remote dogu descriptor lib
cloudogu/k8s-dogu-operator pull request #207
Opened 2024-11-05 15:35 UTC by nroeske

Resolves #204

2024-11-07 13:26 UTC, nhinze23 requested changes

2024-11-15 09:05 UTC, nhinze23 commented
Changelog entry is missing

2024-11-15 12:54 UTC, meiserloh commented on controllers/cesregistry/doguFetcher.go
> +		namespace, name, err := getNamespaceAndNameOfDogu(doguResource)
you could just use QualifiedNameFormString here

2024-11-19 14:57 UTC, nhinze23 commented on controllers/cesregistry/doguFetcher.go
> +	const doguDescriptorMaxRetriesEnv = "DOGU_DESCRIPTOR_MAX_RETRIES"
declare that const outside of the constructor

2024-11-19 16:07 UTC, merged