Add security field to Dogu-CR and generate SecurityContext
cloudogu/k8s-dogu-operator pull request #222
Opened 2024-12-13 16:38 UTC by jelemux

Resolves #221

2024-12-13 16:39 UTC, jelemux commented
Still WIP, do not merge

2024-12-23 08:05 UTC, nhinze23 commented on api/v2/dogu_types.go
> +var AllCapabilities = func() []Capability {
This var would fit better in the cesapp-lib

2024-12-23 08:14 UTC, nhinze23 commented on api/v2/dogu_types_security.go
> +	// type indicates which kind of AppArmor profile will be applied.
```suggestion
	// Type indicates which kind of AppArmor profile will be applied.
```

2024-12-23 08:14 UTC, nhinze23 commented on api/v2/dogu_types_security.go
> +	// localhostProfile indicates a profile loaded on the node that should be used.
```suggestion
	// LocalhostProfile indicates a profile loaded on the node that should be used.
```

2024-12-23 08:18 UTC, nhinze23 commented on api/v2/dogu_types_test.go
> +		{"valid add filled", args{&Dogu{Spec: DoguSpec{Security: Security{Capabilities: Capabilities{Drop: []Capability{core.AuditControl}}}}}}, assert.NoError},
```suggestion
		{"valid drop filled", args{&Dogu{Spec: DoguSpec{Security: Security{Capabilities: Capabilities{Drop: []Capability{core.AuditControl}}}}}}, assert.NoError},
```

2024-12-23 12:21 UTC, nhinze23 commented on controllers/resource/securityContext.go
> +	// We never want those to be true and don't respect the dogu descriptor's privileged flag which is deprecated anyway.
Nice :+1: This flag was only used by the registrator dogu which is no longer needed.

2024-12-23 13:54 UTC, nhinze23 commented on controllers/resource/resource_generator.go
> +				Add:  []corev1.Capability{"CHOWN"},
The init container also needs `DAC_OVERRIDE`.

2025-01-06 14:28 UTC, jelemux commented on api/v2/dogu_types.go
> +var AllCapabilities = func() []Capability {
It is in cesapp-lib. The problem is, that it has the wrong type there. So what we do here is convert it to the type we need.

2025-01-07 14:18 UTC, cesmarvin commented on api/v2/dogu_types.go
> +	allCapabilities := make([]Capability, len(core.AllCapabilities), len(core.AllCapabilities))
🚫 **[checkstyle]** <gosimple> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>S1019: should use make([]Capability, len(core.AllCapabilities)) instead
<!-- __reviewdog__:ChA4ODI0YWY0YTFjYjQ3YmE2EgpjaGVja3N0eWxl -->

2025-01-08 10:06 UTC, nroeske commented on k8s/helm-crd/templates/k8s.cloudogu.com_dogus.yaml
The same comments as in `api/v2/k8s.cloudogu.com_dogus.yaml`

2025-01-10 10:37 UTC, alexander-dammeier requested changes
Nice code! There is a little bit of duplication with the cesapp-lib but the rest looks good to me.

2025-01-10 10:37 UTC, alexander-dammeier commented on controllers/resource/securityContext.go
> +func effectiveCapabilities(dogu *core.Dogu, doguResource *v2.Dogu) []corev1.Capability {
Is this duplicated code? There is already an implementation in cesapp lib:
https://github.com/cloudogu/cesapp-lib/blob/05943e20c25358f2de6e0b041b60b433d3256320/core/dogu_v2.go#L895

Maybe we should change the code in cesapp-lib if it is not reusable at the moment.

2025-01-16 10:58 UTC, merged