Feature/44 expand pvc
cloudogu/k8s-dogu-operator pull request #68
Opened 2022-12-21 08:25 UTC by nhinze23

Resolves #44

2022-12-21 14:00 UTC, Subaro requested changes
Looks already very good. Needs just some small refactors.

2022-12-21 14:00 UTC, Subaro commented on internal/mocks/VolumeManager.go
> +// Code generated by mockery v2.14.0. DO NOT EDIT.
You could run make mocks again to generate mocks for the Async-Step and -Executor.

2022-12-22 07:39 UTC, nhinze23 commented on docs/development/async_operations_de.md
> +der Endzustand je nach Ereignis variieren. Muss ein Step auf eine bestimmte Aktion im Cluster warten kann er so lange ein
The endstate from the step is not fixed. It can be the state from the next step or the startstate from itself to requeue

2022-12-22 10:02 UTC, Subaro commented on docs/development/async_operations_de.md
> +der Endzustand je nach Ereignis variieren. Muss ein Step auf eine bestimmte Aktion im Cluster warten kann er so lange ein
You are right.

2022-12-22 14:12 UTC, Subaro approved these changes

2022-12-22 15:27 UTC, merged